ajuste de workflow v4

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -25,8 +25,22 @@ jobs:
 
       - name: Atualizar kubeconfig
         run: |
-          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}
-
+          if [ -z "${{ secrets.EKS_CLUSTER_NAME }}" ] || [ -z "${{ secrets.AWS_REGION }}" ]; then
+            echo "Error: EKS_CLUSTER_NAME or AWS_REGION is not set."
+            exit 1
+          fi
+          if kubectl get deployment vulnjavaapp; then
+            echo "Deleting existing deployment vulnjavaapp"
+            kubectl delete deployment vulnjavaapp
+          else
+            echo "Deployment vulnjavaapp not found"
+          fi
+          if kubectl get service vulnjavaapp-service; then
+            echo "Deleting existing service vulnjavaapp-service"
+            kubectl delete service vulnjavaapp-service
+          else
+            echo "Service vulnjavaapp-service not found"
+          fi
       - name: Deletar ambiente anterior (opcional)
         run: |
           kubectl delete deployment vulnjavaapp --ignore-not-found
@@ -48,7 +62,6 @@ jobs:
               metadata:
                 labels:
                   app: vulnjavaapp
-                  dynatrace.com/inject: "true"
               spec:
                 containers:
                 - name: vulnerable-java-app
@@ -71,4 +84,6 @@ jobs:
           EOF
 
       - name: Aguardar rollout do deployment
-        run: kubectl rollout status deployment/vulnjavaapp
+        run: kubectl rollout status deployment/vulnjavaapp --timeout=5m
+
+      #test
